### PR TITLE
Put app into temporary whitelist when an high-priority GCM message is received

### PR DESCRIPTION
**Pull request by ale5000-git**
Fix attempt for the issue: https://github.com/microg/android_packages_apps_GmsCore/issues/338
by @ccaapton

### CODE REVIEW

**Comment by ccaapton** [comment]
Yes, your commit https://github.com/a5k-testing/android_packages_apps_GmsCore/pull/1/commits/67de6f41ccf90944d38037ba1815b7333eaf3869 is basically what I previously did.

You should also add a new file /system/etc/permissions/microg.xml:
```
<permissions>
  <allow-in-power-save package="com.google.android.gms" />
</permissions>
```
You can use ` adb shell dumpsys deviceidle whitelist` and ` adb shell dumpsys deviceidle tempwhitelist` to test&verify.

I would be very happy to see "// ToDO: Find out userID" to be resolved, because currently it will not work in multi-user or managed profile scenario.  In fact this is the major reason why I did not push my work upstream.

**Comment by ale5000-git** [comment]
I don't have too much time currently but are you sure that it is `/system/etc/permissions/`?

In my installer I use `/system/etc/sysconfig/` and it works, the file is [here](https://github.com/micro-a5k/microg-unofficial-installer/blob/master/zip-content/files/etc/sysconfig/microg-a5k.xml).

The one of Open GApps is [here](https://github.com/opengapps/all/blob/master/etc/sysconfig/google.xml).

**Comment by ccaapton** [comment]
My rom is lineageos 14.1, and its /system/etc/sysconfig/ is empty, perhaps it is rom-specific.

**Comment by ale5000-git** [comment]
Often even if the folder not exist or is empty by default it will still work if you create it manually, you can test by placing the file and looking in the Android settings if it the battery optimizations are disabled for GmsCore and cannot be enabled.

**Comment by ccaapton** [comment]
According to https://android.googlesource.com/platform/frameworks/base/+/master/core/java/com/android/server/SystemConfig.java both folders are fine.

**Comment by ale5000-git** [comment]
@ccaapton
Can you please repost your comments to [here](https://github.com/microg/android_packages_apps_GmsCore/issues/338)?

Because this repository is only for my tests and it will disappear soon.

**Pull request merged**
